### PR TITLE
Add prettybacon and mocha for specs

### LINKED ISSUE #9: Include pretty_bacon to make output more pretty

### PR DESCRIPTION
**Pull request by segiddins**
Closes #9

### CODE REVIEW

**Comment by alloy** [comment]
:+1:

**Comment by alloy** [comment]
How about adding requires to the spec helper and an example spec that uses Mocha?

**Comment by segiddins** [comment]
Requires were added in the PR already.

**Comment by alloy** [comment]
Ah yeah, I was looking at the file in master, my bad.

**Pull request merged**
